### ISSUE TITLE
python3 implementation

### ISSUE THREAD

**Issue by bigrobinson** [pinga-lab/magnetic-ellipsoid#23]
This is great stuff. Do you guys have an implementation of this for python3, and using your new software libraries (verde, etc.)?

**Comment by birocoles** [comment]
Hi Brian! We do not have an implementation of this for python3 in the new Fatiando. There is some implementations for the gravitational field due to ellipsoids in [Boule](https://www.fatiando.org/boule/latest/index.html).

**Comment by bigrobinson** [comment]
Not complaining here, just curious: Do you still consider this a valid model? If so, why isn't it being supported? Thanks for the work you've done on this.

**Comment by birocoles** [comment]
The model is totally valid. It was developed between 2015-2017 by one of my [master students](https://doi.org/10.6084/m9.figshare.20335221.v1) at that time and we have published a [paper](https://doi.org/10.5194/gmd-10-3591-2017). Since then I have being studying other stuff and that is why the model isn't being supported.

**Comment by bigrobinson** [comment]
Well it's very nice work. I read the paper over the weekend and am looking forward to using this to do some modeling. I did convert the main code and two of the Jupyter cookbooks to Python3 and just ported some of the methods and constants straight from fatiando. If it becomes worthy of a PR, I'll hit you up. Thank you!

**Comment by leouieda** [comment]
@bigrobinson we'd love to have this over in our new library [Choclo](https://github.com/fatiando/choclo). It's meant to house all of our forward modelling with analytic solutions so this would fit right in. Choclo has relatively simple function that calculate the effect of a single source on a single observation point. We can then wrap that in [numba](https://numba.pydata.org/) for performance and use it in Harmonica and other software for both forward modelling and inversion. If you're interested, please feel free to open an issue in Choclo and we can discuss adding this there.

@santisoler has been leading that as a way to bridge the gap between Fatiando and [SimPEG](https://simpeg.xyz/).

**Comment by santisoler** [comment]
It would be awesome to have ellipsoidal sources in Choclo! 🌽 🏉
