### ISSUE TITLE
`*_ignore_missing_prop` tests failing in Linux

### ISSUE THREAD

**Issue by leouieda** [pinga-lab/magnetic-ellipsoid#7]
The three `test_*_ignore_missing_prop()` tests are failing for me using numpy 1.11. 
Do they pass for you under Windows @birocoles?

**Comment by birocoles** [comment]
@leouieda , I have already solved the problems with these tests. Let me know if these tests are still failing for you.

**Comment by leouieda** [comment]
@birocoles everything passes this time
